using Godot;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace YusGameFrame.YusEventSystem;

[Tool]
public partial class YusEventCodeGenerator : RefCounted
{
    private const string GeneratedFilePath = "res://YusGameFrame/YusEventSystem/Generated/YusEventSignals.g.cs";
    private static readonly Regex IdentifierPattern = new("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);

    public static bool Generate(YusEventDefinitionConfig? config)
    {
        if (config == null)
        {
            GD.PushError("YusEventCodeGenerator requires a valid config resource.");
            return false;
        }

        var diagnostics = Validate(config);
        if (diagnostics.Count > 0)
        {
            foreach (var diagnostic in diagnostics)
            {
                GD.PushError($"YusEventSystem generate failed: {diagnostic}");
            }

            return false;
        }

        var content = BuildFileContent(config.Events);
        var fullPath = ProjectSettings.GlobalizePath(GeneratedFilePath);
        var directory = Path.GetDirectoryName(fullPath);
        if (string.IsNullOrEmpty(directory))
        {
            GD.PushError($"YusEventSystem generate failed: invalid output path '{GeneratedFilePath}'.");
            return false;
        }

        Directory.CreateDirectory(directory);
        File.WriteAllText(fullPath, content, new UTF8Encoding(false));

        GD.Print($"YusEventSystem generated: {GeneratedFilePath}");
        return true;
    }

    private static List<string> Validate(YusEventDefinitionConfig config)
    {
        var diagnostics = new List<string>();
        var seenNames = new HashSet<string>(StringComparer.Ordinal);

        for (var i = 0; i < config.Events.Count; i++)
        {
            var item = config.Events[i];
            if (item == null)
            {
                diagnostics.Add($"Entry {i} is null.");
                continue;
            }

            if (string.IsNullOrWhiteSpace(item.EventName))
            {
                diagnostics.Add($"Entry {i} has an empty event name.");
            }
            else if (!IdentifierPattern.IsMatch(item.EventName))
            {
                diagnostics.Add($"Event '{item.EventName}' is not a valid C# identifier.");
            }
            else if (!seenNames.Add(item.EventName))
            {
                diagnostics.Add($"Event '{item.EventName}' is duplicated.");
            }

            if (item.ParameterCount is < 0 or > 3)
            {
                diagnostics.Add($"Event '{item.EventName}' has unsupported parameter count {item.ParameterCount}.");
                continue;
            }

            if (item.ParameterTypes.Count != item.ParameterCount)
            {
                diagnostics.Add($"Event '{item.EventName}' expects {item.ParameterCount} parameter type entries but found {item.ParameterTypes.Count}.");
                continue;
            }

            for (var typeIndex = 0; typeIndex < item.ParameterTypes.Count; typeIndex++)
            {
                var typeName = item.ParameterTypes[typeIndex]?.Trim() ?? string.Empty;
                if (string.IsNullOrWhiteSpace(typeName))
                {
                    diagnostics.Add($"Event '{item.EventName}' has an empty parameter type at index {typeIndex}.");
                }
            }
        }

        return diagnostics;
    }

    private static string BuildFileContent(IEnumerable<YusEventDefinitionItem> definitions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// 此文件由 YusEventCodeGenerator 自动生成，请勿手动修改。");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("using Godot;");
        builder.AppendLine("using System;");
        builder.AppendLine();
        builder.AppendLine("namespace YusGameFrame.YusEventSystem;");
        builder.AppendLine();
        builder.AppendLine("public static partial class YusEventSignals");
        builder.AppendLine("{");
        builder.AppendLine("    internal static void RegisterAll(YusEventSystemService service)");
        builder.AppendLine("    {");

        foreach (var definition in definitions)
        {
            builder.AppendLine($"        service.RegisterEvent({definition.EventName}Event.EventKey);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var definition in definitions)
        {
            AppendEventWrapper(builder, definition);
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendEventWrapper(StringBuilder builder, YusEventDefinitionItem definition)
    {
        var typeNames = definition.ParameterTypes.Select(static typeName => typeName.Trim()).ToArray();
        var parameterList = CreateParameterList(typeNames);
        var actionType = CreateActionType(typeNames);
        var methodArgs = CreateMethodArgumentList(typeNames.Length);

        builder.AppendLine($"    public static class {definition.EventName}Event");
        builder.AppendLine("    {");
        builder.AppendLine($"        internal const string EventKey = \"{definition.EventName}\";");
        builder.AppendLine();
        builder.AppendLine($"        public static void AddListener(Node owner, {actionType} listener)");
        builder.AppendLine("        {");
        builder.AppendLine($"            YusEventSystemService.RequireInstance().AddListener(EventKey, owner, listener);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public static void RemoveListener({actionType} listener)");
        builder.AppendLine("        {");
        builder.AppendLine($"            YusEventSystemService.RequireInstance().RemoveListener(EventKey, listener);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public static void Broadcast({parameterList})");
        builder.AppendLine("        {");
        if (typeNames.Length == 0)
        {
            builder.AppendLine("            YusEventSystemService.RequireInstance().Broadcast(EventKey);");
        }
        else
        {
            builder.AppendLine($"            YusEventSystemService.RequireInstance().Broadcast(EventKey, {methodArgs});");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static string CreateParameterList(IReadOnlyList<string> typeNames)
    {
        if (typeNames.Count == 0)
        {
            return string.Empty;
        }

        var parts = new string[typeNames.Count];
        for (var i = 0; i < typeNames.Count; i++)
        {
            parts[i] = $"{typeNames[i]} arg{i + 1}";
        }

        return string.Join(", ", parts);
    }

    private static string CreateActionType(IReadOnlyList<string> typeNames)
    {
        return typeNames.Count == 0
            ? "Action"
            : $"Action<{string.Join(", ", typeNames)}>";
    }

    private static string CreateMethodArgumentList(int count)
    {
        var parts = new string[count];
        for (var i = 0; i < count; i++)
        {
            parts[i] = $"arg{i + 1}";
        }

        return string.Join(", ", parts);
    }
}
